### ISSUE TITLE
Immediate generation double shifting.

### ISSUE THREAD

**Issue by AdCalleja** [zeeshanrafique009/RISC-V-single-cycle-core-Logisim#6]
I'm finding really helpful this project to understand a basic implementation of a RISC-V core but I'm having some trouble trying to understand the use of a shifter for the B-type and J-type instruction formats. The standard talks about "shifting" 1 bit at the time that the relocation of the bits is being done, thing that you also do.

> The only difference between the S and B formats is that the **12-bit immediate field** is used to **encode
**branch offsets in multiples of 2** in the B format

And

> Similarly, the only difference between the U and J formats is that the 20-bit immediate is shifted
left by 12 bits to form U immediates and by **1 bit to form J immediates**.

The circuit on your project that I'm talking about:
![imagen](https://user-images.githubusercontent.com/45661536/134086557-bf118f6a-0f59-46f7-9ed2-30f196ebc1ae.png)
Is doing a double shift an error or I am not seeing something?

**Comment by zeeshanrafique23** [comment]
I am happy to hear that it is helpful to.
Thanks @AdCalleja for pointing out the issue, yes there should be either 0 padded at LSB or right shifted (not both). There are some known bugs in this implementation and need to be fixed.

**Comment by zeeshanrafique23** [comment]
The issue is resolved. Thanks for pointing it out.
